apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: __SVC__
  namespace: __SVC__
  labels:
    app.kubernetes.io/name: __SVC__
    release: kps
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: __SVC__
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
